---
abstract: 'Send SMS over the internet with gnokii-smsd'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-RemoteGnokii
no_index:
  directory:
    - t
    - inc
requires:
  Config::Any: '0'
  File::Copy: '0'
  File::Slurp: '0'
  File::Temp: '0'
  File::Which: '0'
  Plack::Request: '0'
  perl: '5.014000'
resources:
  repository: https://git.ieval.ro/?p=app-remotegnokii.git
version: 0.000_001
